// ACTION TYPES
const PATH = 'app/wishlist/';

export const TOGGLE_PURCHASED = `${PATH}TOGGLE_PURCHASED`;
export const TOGGLE_FAVORITE = `${PATH}TOGGLE_FAVORITE`;
export const TOGGLE_ADD_ITEM_MODAL = `${PATH}TOGGLE_ADD_ITEM_MODAL`;
